# -*- coding: utf-8 -*-
"""Aula 2 Preparação e Limpeza dos dados .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgiAkIuhNC0OXpr0pUN1_lx4Y2HzmCgQ
"""



import pandas as pd

df =pd.read_csv ("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

#importação da tabela com biblioteca pandas as ps

df.head(10)

# invocação da tabela com 10 colunas

df.info()

#informações

# 1. Definir os dicionários de tradução para colunas e categorias
column_translation = {
    'work_year': 'Ano',
    'experience_level': 'nivel_experiencia', # Temporarily keep this before final rename to Senioridade
    'employment_type': 'tipo_emprego',      # Temporarily keep this before final rename to Contrato de trabalho
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda_salario',
    'salary_in_usd': 'salario_em_usd',
    'employee_residence': 'residencia_funcionario',
    'remote_ratio': 'taxa_remoto',         # Temporarily keep this before final rename to Remoto
    'company_location': 'local_empresa',
    'company_size': 'porte_empresa'        # Temporarily keep this before final rename to Tamanho da empresa
}

nivel_experiencia_translation = {
    'SE': 'Sênior',
    'MI': 'Médio',
    'EN': 'Iniciante',
    'EX': 'Executivo'
}

tipo_emprego_translation = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Período',
    'FL': 'Freelancer'
}

porte_empresa_translation = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}

remote_translation = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Totalmente Remoto'
}

# 2. Aplicar a renomeação inicial das colunas
df = df.rename(columns=column_translation)

# 3. Aplicar as traduções das categorias e renomear as colunas finais
df['nivel_experiencia'] = df['nivel_experiencia'].replace(nivel_experiencia_translation)
df = df.rename(columns={'nivel_experiencia': 'Senioridade'})

df['tipo_emprego'] = df['tipo_emprego'].replace(tipo_emprego_translation)
df = df.rename(columns={'tipo_emprego': 'Contrato de trabalho'})

df['porte_empresa'] = df['porte_empresa'].replace(porte_empresa_translation)
df = df.rename(columns={'porte_empresa': 'Tamanho da empresa'})

df['taxa_remoto'] = df['taxa_remoto'].replace(remote_translation)
df = df.rename(columns={'taxa_remoto': 'Remoto'})

print("Colunas do DataFrame após todas as correções:")
print(df.columns)

print("\nVerificando as contagens de valores para as colunas corrigidas:")
print("\nSenioridade:")
print(df['Senioridade'].value_counts())
print("\nContrato de trabalho:")
print(df['Contrato de trabalho'].value_counts())
print("\nTamanho da empresa:")
print(df['Tamanho da empresa'].value_counts())
print("\nRemoto:")
print(df['Remoto'].value_counts())

df.describe()

#descrição aprofundada

df.shape
# total de linha e colunas da base (Tuplas:valores agrupados de elementos )

# criando variaveis para melhor vizualização

linhas, colunas = df.shape[0], df.shape[1]

print("numeros de linhas:" , linhas)
print("numeros de colunas:" , colunas)

# Gemini tradução de coluna

df.columns

df['Contrato de trabalho'].value_counts()

df["Ano"].value_counts()

df["Senioridade"].value_counts()

df.columns

df["Contrato de trabalho"].value_counts()

df["cargo"].value_counts()

df["salario"].value_counts()

df["moeda_salario"].value_counts()

df['salario_em_usd'].value_counts()

df['Contrato de trabalho'].value_counts()

df["Remoto"].value_counts()

df["local_empresa"].value_counts()

df['Tamanho da empresa'].value_counts()

df.head()

df.describe(include="object")

import pandas as pd
df =pd.read_csv ("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")
df.isnull()

